#!/bin/bash

# 获取内存使用量（单位：GiB）
used_mem_raw=$(LC_ALL=C free -m | awk '/Mem/ {printf "%.1f", $3/1024}')
used_mem=${used_mem_raw/.*}

color="#000000"
if [ "$used_mem" -gt 10 ]; then
    color="#FF0000"
elif [ "$used_mem" -gt 5 ]; then
    color="#FFA500"
fi

echo "<span color='$color'> ${used_mem_raw}G</span>"


