#!/bin/bash

# Get volume percentage
volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -n 1)

# Get mute status
mute_status=$(pactl get-sink-mute @DEFAULT_SINK@)

# Check if muted
if [[ $mute_status == *"yes"* ]]; then
  echo "<span color='#FF0000'> Muted</span>"
else
  icon=""
  if [ "$volume" -gt 50 ]; then
    icon=""
  elif [ "$volume" -gt 0 ]; then
    icon=""
  else
    icon=""
  fi
  echo "$icon $volume%"
fi
